In [10]:
import pandas as pd
import os
from os.path import exists


def process_emdat( repo_path=".../laos-climate-change"):
    if not exists(repo_path + "/data"):
        os.makedirs(repo_path + "/data")
    
    if not exists(repo_path + "/data/emdat.xlsx"):
        raise NotImplementedError()

    df = pd.read_excel(repo_path + "/data/emdat.xlsx", sheet_name="EM-DAT Data")

    prob_cols = [
        "Drought",
        "Earthquake",
        "Extreme temperature",
        "Flood",
        "Storm",
        "Wildfire",
        "Volcanic activity",
        "Mass Movement (Dry)",
        "Mass Movement (Wet)",]

    intensity_cols = [
        "Country",
        "Start Year",
        "Total Deaths",
        "No. Injured",
        "No. Affected",
        "No. Homeless",
        "Total Affected",
        "Reconstruction Costs ('000 US$)",
        "Reconstruction Costs, Adjusted ('000 US$)",
        "Insured Damage ('000 US$)",
        "Insured Damage, Adjusted ('000 US$)",
        "Total Damage ('000 US$)",
        "Total Damage, Adjusted ('000 US$)",
        "CPI",
    ]

    df2 = df.copy()[intensity_cols]

    df = (
        df.query("`Disaster Type` in @prob_cols")
        .groupby(["Disaster Type", "ISO", "Start Year"])
        .size()
        .unstack("Disaster Type")
        .fillna(0)
        .reset_index()
    ).copy()


    disasters_found = [
        "Drought",
        "Earthquake",
        "Extreme temperature",
        "Flood",
        "Storm",
        "Volcanic activity",
        "Wildfire",
    ]

    df[disasters_found] = df[disasters_found].astype(int).copy()

    df.rename(columns={"ISO": "Country"}, inplace=True)
    df2.rename(columns={"ISO": "Country"}, inplace=True)

    df_prob = df.copy().set_index(["Country", "Start Year"]).sort_index()
    df_inten = df2.copy().set_index(["Country", "Start Year"]).sort_index()
    
    df_prob.to_csv(repo_path + "/data/probability_data_set.csv")
    df_inten.to_csv(repo_path + "/data/intensity_data_set.csv" )
    return df_prob,  df_inten

In [17]:
 df_prob,  df_inten = process_emdat("C:/Users/camil/Dropbox/Servicios/OECD-GGGI/laos-climate-change")

In [19]:
df_inten

                        Total Deaths  No. Injured  No. Affected  No. Homeless  \
Country     Start Year
Afghanistan 2000               507.0          NaN           NaN           NaN
            2000                16.0          NaN          11.0           NaN
            2000                19.0          NaN        1604.0           NaN
            2000                15.0          NaN         613.0           NaN
            2000                40.0         40.0           NaN           NaN
...                              ...          ...           ...           ...
Zimbabwe    2022                 NaN          NaN        3000.0           NaN
            2022                35.0         71.0           NaN           NaN
            2022               750.0       6551.0           NaN           NaN
            2023                 2.0          NaN           NaN           NaN
            2023               108.0        963.0           NaN           NaN

                        Total Affected  Reconstruction Costs ('000 US$)  \
Country     Start Year
Afghanistan 2000                   NaN                              NaN
            2000                  11.0                              NaN
            2000                1604.0                              NaN
            2000                 613.0                              NaN
            2000                  40.0                              NaN
...                                ...                              ...
Zimbabwe    2022                3000.0                              NaN
            2022                  71.0                              NaN
            2022                6551.0                              NaN
            2023                   NaN                              NaN
            2023                 963.0                              NaN

                        Reconstruction Costs, Adjusted ('000 US$)  \
Country     Start Year
Afghanistan 2000                                              NaN
            2000                                              NaN
            2000                                              NaN
            2000                                              NaN
            2000                                              NaN
...                                                           ...
Zimbabwe    2022                                              NaN
            2022                                              NaN
            2022                                              NaN
            2023                                              NaN
            2023                                              NaN

                        Insured Damage ('000 US$)  \
Country     Start Year
Afghanistan 2000                              NaN
            2000                              NaN
            2000                              NaN
            2000                              NaN
            2000                              NaN
...                                           ...
Zimbabwe    2022                              NaN
            2022                              NaN
            2022                              NaN
            2023                              NaN
            2023                              NaN

                        Insured Damage, Adjusted ('000 US$)  \
Country     Start Year
Afghanistan 2000                                        NaN
            2000                                        NaN
            2000                                        NaN
            2000                                        NaN
            2000                                        NaN
...                                                     ...
Zimbabwe    2022                                        NaN
            2022                                        NaN
            2022                                        NaN
            2023                                        NaN
            2023                                        NaN

                        Total Damage ('000 US$)  \
Country     Start Year
Afghanistan 2000                            NaN
            2000                            NaN
            2000                            NaN
            2000                            NaN
            2000                            NaN
...                                         ...
Zimbabwe    2022                            NaN
            2022                            NaN
            2022                            NaN
            2023                            NaN
            2023                            NaN

                        Total Damage, Adjusted ('000 US$)         CPI
Country     Start Year
Afghanistan 2000                                      NaN   56.514291
            2000                                      NaN   56.514291
            2000                                      NaN   56.514291
            2000                                      NaN   56.514291
            2000                                      NaN   56.514291
...                                                   ...         ...
Zimbabwe    2022                                      NaN   96.046342
            2022                                      NaN   96.046342
            2022                                      NaN   96.046342
            2023                                      NaN  100.000000
            2023                                      NaN  100.000000

[15772 rows x 12 columns]

In [16]:
df = pd.read_excel(repo_path + "/data/emdat.xlsx", sheet_name="EM-DAT Data")

prob_cols = [
    "Drought",
    "Earthquake",
    "Extreme temperature",
    "Flood",
    "Storm",
    "Wildfire",
    "Volcanic activity",
    "Mass Movement (Dry)",
    "Mass Movement (Wet)",]

intensity_cols = [
    "Country",
    "Start Year",
    "Total Deaths",
    "No. Injured",
    "No. Affected",
    "No. Homeless",
    "Total Affected",
    "Reconstruction Costs ('000 US$)",
    "Reconstruction Costs, Adjusted ('000 US$)",
    "Insured Damage ('000 US$)",
    "Insured Damage, Adjusted ('000 US$)",
    "Total Damage ('000 US$)",
    "Total Damage, Adjusted ('000 US$)",
    "CPI",
]

df2 = df.copy()[intensity_cols]

df = (
    df.query("`Disaster Type` in @prob_cols")
    .groupby(["Disaster Type", "ISO", "Start Year"])
    .size()
    .unstack("Disaster Type")
    .fillna(0)
    .reset_index()
).copy()


disasters_found = [
    "Drought",
    "Earthquake",
    "Extreme temperature",
    "Flood",
    "Storm",
    "Volcanic activity",
    "Wildfire",
]

df[disasters_found] = df[disasters_found].astype(int).copy()

df.rename(columns={"ISO": "Country"}, inplace=True)
df2.rename(columns={"ISO": "Country"}, inplace=True)

df_prob = df.copy().set_index(["Country", "Start Year"]).sort_index()
df_inten = df2.copy().set_index(["Country", "Start Year"]).sort_index()

NameError: name 'repo_path' is not defined

In [15]:
if not exists(repo_path + "/data"):
        os.makedirs(repo_path + "/data")
    
    if not exists(repo_path + "/data/emdat.xlsx"):
        raise NotImplementedError()

    df = pd.read_excel(repo_path + "/data/emdat.xlsx", sheet_name="EM-DAT Data")

    prob_cols = [
        "Drought",
        "Earthquake",
        "Extreme temperature",
        "Flood",
        "Storm",
        "Wildfire",
        "Volcanic activity",
        "Mass Movement (Dry)",
        "Mass Movement (Wet)",]

    intensity_cols = [
        "Country",
        "Start Year",
        "Total Deaths",
        "No. Injured",
        "No. Affected",
        "No. Homeless",
        "Total Affected",
        "Reconstruction Costs ('000 US$)",
        "Reconstruction Costs, Adjusted ('000 US$)",
        "Insured Damage ('000 US$)",
        "Insured Damage, Adjusted ('000 US$)",
        "Total Damage ('000 US$)",
        "Total Damage, Adjusted ('000 US$)",
        "CPI",
    ]

    df2 = df.copy()[intensity_cols]

    df = (
        df.query("`Disaster Type` in @prob_cols")
        .groupby(["Disaster Type", "ISO", "Start Year"])
        .size()
        .unstack("Disaster Type")
        .fillna(0)
        .reset_index()
    ).copy()


    disasters_found = [
        "Drought",
        "Earthquake",
        "Extreme temperature",
        "Flood",
        "Storm",
        "Volcanic activity",
        "Wildfire",
    ]

    df[disasters_found] = df[disasters_found].astype(int).copy()

    df.rename(columns={"ISO": "Country"}, inplace=True)
    df2.rename(columns={"ISO": "Country"}, inplace=True)

    df_prob = df.copy().set_index(["Country", "Start Year"]).sort_index()
    df_inten = df2.copy().set_index(["Country", "Start Year"]).sort_index()

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)